---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nginx
  name: deployment-mynginx2
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: myapp2
  replicas: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: myapp2
    spec:
      containers:
      - image: sgrsaga/mytestimage:green
        imagePullPolicy: Always
        name: myapp
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: nginx
  name: service-myapp2
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ap-south-1:598792377165:certificate/3ae35aa3-101e-4a0e-99d6-626a057eb855
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: myapp2
