piVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: nginx
spec:
  ingressClassName: nginx
  rules:
  - host:
    http:
       paths:
          - path: /
            pathType: Prefix
            backend:
               service:
                  name: mynginx-svc
                  port: 
                    number: 80