apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: myapp
    app.kubernetes.io/name: myapp
  name: mydep
  namespace: myns
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
          - containerPort: 80
            name: web-port
