---
apiVersion: v1
kind: Service
metadata:
  name: my-svc
spec:
  selector:
    app.kubernetes.io/name: myapp
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    targetPort: web-port
